#!/bin/sh
#
# @name Typhoon H480 SITL
#
# @type Hexarotor x
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MAV_TYPE 13

param set-default SYS_CTRL_ALLOC 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 7


param set-default MC_PITCHRATE_P 0.0800
param set-default MC_PITCHRATE_I 0.0400
param set-default MC_PITCHRATE_D 0.0010
param set-default MC_PITCH_P 9.0
param set-default MC_ROLLRATE_P 0.0800
param set-default MC_ROLLRATE_I 0.0400
param set-default MC_ROLLRATE_D 0.0010
param set-default MC_ROLL_P 9.0

param set-default MPC_XY_VEL_I_ACC 4
param set-default MPC_XY_VEL_P_ACC 3

param set-default RTL_DESCEND_ALT 10
param set-default RTL_LAND_DELAY 0

# param set-default TRIG_INTERFACE 3
# param set-default TRIG_MODE 4
# param set-default MNT_MODE_IN 0
# param set-default MAV_PROTO_VER 2


param set-default CA_ROTOR0_PX 0.0
param set-default CA_ROTOR0_PY 1.0
param set-default CA_ROTOR0_KM -0.05
# #change of orientation
# param set-default CA_ROTOR0_AX 1.0000
# param set-default CA_ROTOR0_AY 0.0000
# param set-default CA_ROTOR0_AZ 0.0000

param set-default CA_ROTOR1_PX 0.0
param set-default CA_ROTOR1_PY -1.0
param set-default CA_ROTOR1_KM 0.05
#change of orientation
# param set-default CA_ROTOR1_AX 1.0000
# param set-default CA_ROTOR1_AY 0.0000
# param set-default CA_ROTOR1_AZ 0.0000

param set-default CA_ROTOR2_PX 0.866025
param set-default CA_ROTOR2_PY -0.5
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.866025
param set-default CA_ROTOR3_PY 0.5
param set-default CA_ROTOR3_KM 0.05
param set-default CA_ROTOR4_PX 0.866025
param set-default CA_ROTOR4_PY 0.5
param set-default CA_ROTOR4_KM 0.05
param set-default CA_ROTOR5_PX -0.866025
param set-default CA_ROTOR5_PY -0.5
param set-default CA_ROTOR5_KM -0.05
param set-default CA_ROTOR6_PX 0.0
param set-default CA_ROTOR6_PY 0.0
param set-default CA_ROTOR6_PZ 0.0
param set-default CA_ROTOR6_KM 0.00 #assuming the moment is very low else 0.05
param set-default CA_ROTOR6_AX -1.0
param set-default CA_ROTOR6_AY 0.0
param set-default CA_ROTOR6_AZ 0.0
param set-default CA_ROTOR6_CT 3.25

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 106
param set-default PWM_MAIN_FUNC7 107



#disable MC desaturation which improves attitude tracking
param set-default CA_METHOD 1

# disable attitude failure detection
param set-default FD_FAIL_P 0
param set-default FD_FAIL_R 0

#Set omni parameters
param set OMNI_ATT_MODE 1

set MIXER skip
set MIXER_AUX none
